
services:
  whisper-streaming:
    build:
      context: .
    image: alexmickelson/whisper-streaming:latest
    container_name: whisper-streaming
    volumes:
      - ./cache:/app/cache
    env_file:
      # HF_TOKEN=your read only token
      # accept terms at 
      # - https://huggingface.co/pyannote/segmentation
      # - https://huggingface.co/pyannote/embedding
      # - https://huggingface.co/pyannote/embedding-3.0
      - .env
    command: |
      bash -c '
        uv run whisperlivekit-server \
          --model tiny.en \
          --host 0.0.0.0 \
          --port 8000 \
          --model_cache_dir /app/cache
      '
    ports:
      - 8000:8000
    devices:
      - nvidia.com/gpu=all
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities: [gpu]
    # runtime: nvidia